server:
  port: 9999

spring:
  data:
    mongodb:
#      uri: mongodb://172.31.10.64/mqtt
      uri: mongodb://mqtt:mqtt@172.31.10.64:27017/mqtt
      options:
        min-connections-per-host: 20
        max-connections-per-host: 20
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idel-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15

# log4j2
logging:
  config: classpath:log4j2.yml

mqtt:
  # 客户端信息
  host: tcp://127.0.0.1:1883
  username: mqtt
  password: 123456
  cleansession: false
  # 如果非localhost，需要在etc/acl.conf中配置规则允许此client获取 $SYS/# 消息
  clientid: consumer-publisher
  # 业务消息订阅
  bizclientid: mqtt-biz
  biztopic:
  # rinnai/SR/01/SR/F0FE6BAE428E/res/
  - /+/+/upInfo
  - /+/+/notify
  - /+/+/query
  # 系统消息订阅，topic参考 https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics
  sysclientid: mqtt-sys
  systopic:
  # $SYS/brokers/emqttd-linnei@10.45.33.195/clients/a:rinnai:SR:01:SR:186582626671565159163590/connected
  - $SYS/brokers/+/clients/+/connected
  - $SYS/brokers/+/clients/+/disconnected

