server:
  port: 9090

spring:
  data:
    mongodb:
      uri: mongodb://localhost/mqtt
      port: 27017
      username:
      password:

# log4j2
logging:
  config: classpath:log4j2.yml

mqtt:
  # 客户端信息
  host: tcp://127.0.0.1:1883
  username: mqtt-kunbu
  password: 123456
  cleansession: false
  # 如果非localhost，需要在etc/acl.conf中配置规则允许此client获取 $SYS/# 消息
  clientid: consumer-publisher
  # 业务消息订阅
  bizclientid: consumer-linnei-subscriber
  biztopic:
  # rinnai/SR/01/SR/F0FE6BAE428E/res/
  - kunbu/linnei/+/bsc/
  - kunbu/linnei/+/log/
  - kunbu/linnei/+/inf/
  # 系统消息订阅，topic参考 https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics
  sysclientid: consumer-sys-subscriber
  systopic:
  # $SYS/brokers/emqttd-linnei@10.45.33.195/clients/a:rinnai:SR:01:SR:186582626671565159163590/connected
  - $SYS/brokers/+/clients/+/connected
  - $SYS/brokers/+/clients/+/disconnected

